input_info:
  input_source: ../reference_data/eir-transformer/df_grs.csv
  input_name: biomarker_inputs
  input_type: tabular
input_type_info:
  input_con_columns:
  - Cholesterol
  - LDL_direct
  - Glycated_haemoglobin_HbA1c
  - Alanine_aminotransferase
  - Aspartate_aminotransferase
  - Apolipoprotein_A
  - Apolipoprotein_B_BIOCH
  - Gamma_glutamyltransferase
  - Alkaline_phosphatase
  - Albumin_BIOCH
  - Total_protein
  - Direct_bilirubin
  - Total_bilirubin
  - C_reactive_protein
  - Urate
  - Calcium
  - Phosphate
  - Creatinine_BIOCH
  - Cystatin_C
  - Urea
  - IGF_1
  - Vitamin_D
  - Lipoprotein_A
  modality_dropout_rate: 0.0
model_config:
  model_type: tabular
