output_info:
  output_source: ../reference_data/eir-transformer/df_ehr.csv
  output_name: ehr
  output_type: sequence

model_config:
  embedding_dim: 64
  model_init_config:
    num_layers: 4

output_type_info:
        sampling_strategy_if_longer: "uniform"
        max_length: 64
        split_on: " "
        min_freq: 10