output_info:
  output_source: ../reference_data/eir-transformer/df_ehr_test.csv
  output_name: ehr
  output_type: sequence
output_type_info:
  sampling_strategy_if_longer: uniform
  max_length: 64
  split_on: ' '
  min_freq: 10
model_config:
  embedding_dim: 64
  model_init_config:
    num_layers: 4
sampling_config:
  generated_sequence_length: 128
  n_eval_inputs: 10
  manual_inputs:
  - ehr: SEX_2 [VISIT_START] AGE_59 LAB_HDL_cholesterol_92% LAB_LDL_Cholesterol_88%
      LAB_Total_Triglycerides_18% [VISIT_END]
