- input_info:
    input_name: ehr
    input_source: null
    input_type: sequence
  input_type_info:
    adaptive_tokenizer_max_vocab_size: null
    max_length: 64
    min_freq: 10
    mixing_subtype: mixup
    modality_dropout_rate: 0.0
    sampling_strategy_if_longer: uniform
    split_on: ' '
    tokenizer: null
    tokenizer_language: null
    vocab_file: null
  interpretation_config: null
  model_config:
    embedding_dim: 64
    freeze_pretrained_model: false
    masked: false
    model_init_config:
      dim_feedforward: auto
      dropout: 0.1
      num_heads: 8
      num_layers: 4
    model_type: eir-input-sequence-from-linked-output-default
    pool: null
    position: encode
    position_dropout: 0.1
    pretrained_model: false
    window_size: 0
  pretrained_config: null
  tensor_broker_config: null
